[package]
name = "rust-api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
lapin = "2.3"
axum = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1.0"
futures-lite = "2.6.0"
