version: '3.8'

services:
  rust-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder  # Use builder stage for development
    volumes:
      - .:/app
      - /app/target  # Anonymous volume for target directory
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    command: cargo watch -x run  # Hot reload with cargo-watch
    
  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    ports:
      - "15672:15672"   # Expose management UI for development 