name: Deploy Docker App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rust-api:latest

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          cat <<EOF > ~/.ssh/config
          Host ec2-deploy
            HostName ${{ secrets.EC2_HOST }}
            User ${{ secrets.EC2_USERNAME }}
            Port ${{ secrets.EC2_PORT }}
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          EOF

      - name: Deploy and Run on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            set -e

                    # --- TAMBAHKAN BARIS DEBUG DI SINI ---
            echo "--> Debug: Checking secrets received on EC2."
            echo "--> Username from secret is: [${DOCKERHUB_USERNAME}]"
            echo "--> Token from secret is: [${DOCKERHUB_TOKEN:0:4}...]" # Hanya cetak 4 karakter pertama token untuk keamanan
            # -------------------------------------
              
            TARGET_DIR="/srv/rust-api"
            COMPOSE_FILE_PATH="$TARGET_DIR/docker-compose.prod.yml"

            echo "--> Preparing directory $TARGET_DIR"
            sudo mkdir -p $TARGET_DIR
            sudo chown $USER:$USER $TARGET_DIR
            cd $TARGET_DIR

            echo "--> Creating docker-compose.prod.yml"
            # Kita akan membuat file langsung di sini, lebih sederhana dan andal
            cat << EOF > "$COMPOSE_FILE_PATH"
            services:
              rust-api:
                image: \${DOCKER_IMAGE_NAME}:\${IMAGE_TAG:-latest}
                ports:
                  - "\${PORT}:\${PORT}"
                environment:
                  - PORT=\${PORT}
                  - RABBITMQ_URL=amqp://\${RABBITMQ_USER}:\${RABBITMQ_PASS}@rabbitmq:5672
                depends_on:
                  rabbitmq:
                    condition: service_healthy
                restart: unless-stopped

              rabbitmq:
                image: rabbitmq:3.12-management-alpine
                ports:
                  - "\${RABBITMQ_PORT}:\${RABBITMQ_PORT}"
                  - "\${RABBITMQ_MANAGEMENT_PORT}:\${RABBITMQ_MANAGEMENT_PORT}"
                environment:
                  - RABBITMQ_DEFAULT_USER=\${RABBITMQ_USER}
                  - RABBITMQ_DEFAULT_PASS=\${RABBITMQ_PASS}
                volumes:
                  - rabbitmq_data:/var/lib/rabbitmq
                restart: unless-stopped

            volumes:
              rabbitmq_data:
                driver: local

            networks:
              default:
                driver: bridge
            EOF

            echo "--> Creating .env file"
            # Sekarang shell di EC2 bisa membaca variabel dari 'env' di atas
            cat << EOL > .env
            PORT=$PORT
            RABBITMQ_USER=$RABBITMQ_USER
            RABBITMQ_PASS=$RABBITMQ_PASS
            RABBITMQ_PORT=$RABBITMQ_PORT
            RABBITMQ_MANAGEMENT_PORT=$RABBITMQ_MANAGEMENT_PORT
            DOCKER_IMAGE_NAME=$DOCKERHUB_USERNAME/rust-api
            IMAGE_TAG=latest
            EOL

            echo "--> Logging in to Docker Hub on the EC2 server"
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

            echo "--> Stopping existing containers..."
            docker compose -f "$COMPOSE_FILE_PATH" down

            echo "--> Pulling latest images..."
            docker compose -f "$COMPOSE_FILE_PATH" pull

            echo "--> Starting new containers..."
            docker compose -f "$COMPOSE_FILE_PATH" up -d

            echo "--> Final container status:"
            docker compose -f "$COMPOSE_FILE_PATH" ps
